gcp:
  project: jason-hsbc
  region: europe-west2

proxy:
  http: http://10.0.1.223:7890
  https: http://10.0.1.223:7890
deepseek:
  api-key: "DEEPSEEK_API_KEY"
  base-url: "https://api.deepseek.com"
  
database:
  host: "127.0.0.1" # Connect to the Cloud SQL Auth Proxy sidecar
  port: 5432
  dbname: "default_db"
  user: "nvd11"
  password_env_var: "DB_PASSWORD"
  base-url: "https://api.deepseek.com"

gemini:
  api-key: "GEMINI_API_KEY"
  model-name: "gemini-2.5-pro"
  temperature: 0.7

modeling:
  model1:
    table1: DS1.tb_model1_house_price
